import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { PageTemplate, Search, Character } from '@/components';
import Styles from '../styles/internals.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <PageTemplate>
        <div className={Styles.content}>
          <h1>Encontre opções em Delivery próximos à você.</h1>

          <Search />

          <h2>
            Descubra seu novo Delivery favorito. Milhares de opções a um clique.
          </h2>
        </div>
        <Character />
      </PageTemplate>
    </div>
  );
}
